### ISSUE TITLE
Implement redirect options

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka.curl#2]
https://ec.haxx.se/http/http-redirects
https://github.com/dakrone/clj-http#redirects

**Comment by rymndhng** [comment]
Is the desire to match the same redirect options as `cli-http`?

**Comment by borkdude** [comment]
@rymndhng Before we didn't include the `-L` option by default, now we do. Maybe that's already enough for now?

**Comment by rymndhng** [comment]
I think it's enough for now. 

I don't think we should implement `:redirect-strategy` because it's specific to `Apache HttpClient`. 

As for tracing redirects in the response object, I've added support for including the redirect response in #6. We can discuss this feature as part of that PR.
