### ISSUE TITLE
Add documentation for data-raw

### ISSUE THREAD

**Issue by Heliosmaster** [borkdude/babashka.curl#24]
I've needed to use the following syntax

```clojure
(curl/put address
          {:data-raw {"foo" ["bar" "baz"]}
           :throw false
           :debug true
           :raw-args ["-k"]})
```

So it'd be good to add some examples to the README as well

**Comment by borkdude** [comment]
@Heliosmaster Can you explain me what this examples does and why you need `:data-raw`? I don't think this is part of the public API yet.

**Comment by Heliosmaster** [comment]
Workaround to not have to stringify the json payload and pass it to `:body` :-p

**Comment by borkdude** [comment]
I'm not sure if I understand your use case without more details, but so far it doesn't sound very compelling?

**Comment by borkdude** [comment]
If you are already using `:raw-args` why don't you just pass the data you want using a raw arg?

**Comment by Heliosmaster** [comment]
Not disagreeing with anything you just said. This issue was mainly with the fact that i didn't think that `data-raw` wasn't public on purpose, but it just lacked documentation.
