### ISSUE TITLE
Downloading binaries

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka.curl#3]
@sogaiu tried to download a binary as follows, which didn't work:

```
(spit "foo.zip" (curl/get ...))
```

This might be because the bits get converted to UTF-8 or something along the way

For downloading binary files one has to use the `:raw-args` option with `["-o" "filename.zip"]`. Maybe it would be nice to support this as a proper option (called `:out`?).
We could also implement an option that returns the raw stream: `{:as :stream}`

**Comment by borkdude** [comment]
Implemented the `{:as :stream}` option.

**Comment by kxygk** [comment]
In case someone comes across this. This option doesn't seem to actually allow you to `spit` to file (maybe I'm doing it wrong). The file will just read something like 

    java.io.SequenceInputStream@3c8441e2

However, the example in the README does work
    
    (io/copy
      (:body (curl/get "https://github.com/babashka/babashka/raw/master/logo/icon.png"
        {:as :bytes}))
      (io/file "icon.png"))

And I'm guessing the `clojure.java.io` is baked into `babashka` (I confirmed it works on the JVM and through `bb`)

PS: I'm using this lib b/c I need to get files from an FTP server - which `babashka.http-client` doesn't seem to do

**Comment by borkdude** [comment]
`spit` only works with text

**Comment by kxygk** [comment]
Oh! My bad there!

Seems obvious in retrospect! Thank you so much :))
